ALCOHOL                  618 N    
AUTOMOBILE               607 N    
BAG                      603 N    
BALL                     615 N    
BALLOON                  623 N    
BARN                     614 N    
BASKET                   606 N    
BATH                     600 N    
BEACH                    612 N    
BED                      635 N    
BEDROOM                  615 N    
BEEF                     637 N    
BELL                     620 N    
BELLY                    630 N    
BELT                     602 N    
BENCH                    614 N    
BIRD                     602 N    
BLANKET                  622 N    
BLOOD                    613 N    
BOAT                     637 N    
BOOK                     609 N    
BOY                      609 N    
BREAD                    622 N    
BRICK                    610 N    
BRIDGE                   623 N    
BUTTER                   618 N    
BUTTON                   613 N    
CAKE                     624 N    
CAMERA                   627 N    
CANCER                   615 N    
CANDY                    602 N    
CAR                      622 N    
CARDINAL                 600 N    
CAT                      615 N    
CATTLE                   600 N    
CEILING                  606 N    
CEMENT                   646 N    
CEREAL                   637 N    
CHAIR                    606 N    
CHICKEN                  614 N    
CIGARETTE                607 N    
CLAY                     606 N    
COAT                     601 N    
COFFEE                   613 N    
COLLAR                   622 N    
COTTON                   608 N    
COW                      621 N    
CREAM                    621 N    
DAD                      603 N    
DEER                     631 N    
DENTIST                  607 N    
DOG                      610 N    
DOOR                     606 N    
DOUGH                    627 N    
DRUM                     602 N    
EAR                      640 N    
EGG                      613 N    
ELBOW                    607 N    
EYE                      634 N    
FEET                     642 N    
FILM                     604 N    
FLAG                     606 N    
FOREST                   609 N    
FOX                      605 N    
FRUIT                    612 N    
FUR                      601 N    
FURNACE                  600 N    
GIN                      639 N    
GIRL                     607 N    
GLASS                    635 N    
GUN                      612 N    
HAND                     604 N    
HAT                      601 N    
HAWK                     623 N    
HAY                      623 N    
HEAD                     603 N    
HEART                    605 N    
HEN                      631 N    
HONEY                    611 N    
HORN                     618 N    
HORSE                    613 N    
HOUSE                    608 N    
ICE                      621 N    
INDIAN                   622 N    
JACKET                   635 N    
JAW                      617 N    
JEEP                     622 N    
JERSEY                   621 N    
KEY                      612 N    
KNIFE                    612 N    
LAMP                     615 N    
LAND                     604 N    
LANTERN                  630 N    
LEG                      626 N    
LEMON                    608 N    
LION                     627 N    
LIQUOR                   630 N    
LIVER                    617 N    
MAN                      618 N    
MARBLE                   611 N    
MEAL                     602 N    
MILK                     670 N    
MIRROR                   605 N    
MOUNTAIN                 616 N    
MOUSE                    624 N    
MUD                      605 N    
NEEDLE                   608 N    
NOSE                     628 N    
ONION                    632 N    
ORANGE                   601 N    
PENCIL                   617 N    
PENNY                    606 N    
PHONE                    624 N    
PIANO                    615 N    
PIE                      613 N    
PILL                     610 N    
PIN                      600 N    
PIPE                     602 N    
POND                     623 N    
PONY                     611 N    
POTATO                   629 N    
RABBIT                   635 N    
RADIO                    615 N    
RAIN                     600 N    
RIBBON                   600 N    
RICE                     608 N    
RIFLE                    606 N    
ROCK                     600 N    
ROPE                     608 N    
ROSE                     608 N    
RUG                      611 N    
SADDLE                   603 N    
SEED                     611 N    
SHED                     611 N    
SHEEP                    622 N    
SHEET                    608 N    
SHIP                     615 N    
SHIRT                    616 N    
SHOE                     600 N    
SKIN                     614 N    
SKIRT                    614 N    
SNAKE                    621 N    
SNOW                     618 N    
SOUP                     615 N    
STATUE                   600 N    
STEAK                    646 N    
STICK                    604 N    
STOMACH                  617 N    
STONE                    614 N    
STRAW                    603 N    
SUGAR                    620 N    
SUN                      617 N    
TABLE                    604 N    
TAIL                     613 N    
TEA                      609 N    
TEETH                    618 N    
TELEPHONE                619 N    
TENT                     608 N    
THERMOMETER              612 N    
THREAD                   607 N    
THUMB                    638 N    
TOBACCO                  609 N    
TONGUE                   634 N    
TOOTH                    619 N    
TREE                     604 N    
TYPEWRITER               611 N    
VAN                      606 N    
VEGETABLE                602 N    
VIOLIN                   626 N    
WALNUT                   642 N    
WATER                    616 N    
WHISKEY                  604 N    
WINDOW                   609 N    
WINE                     621 N    
WOOD                     606 N    
WOOL                     608 N    
