ABANDONMENT              272 N    
ABILITY                  273 N    
ABUNDANCE                267 N    
ACCORDANCE               270 N    
ACCUMULATION             285 N    
ADOLESCENCE              267 N    
ADVANTAGE                282 N    
ADVICE                   291 N    
AFFECTION                280 N    
AMAZEMENT                277 N    
AMBITION                 281 N    
ANALOGY                  247 N    
ANTICIPATION             288 N    
ANXIETY                  241 N    
APPROVAL                 267 N    
ARE                      195 N    
AS                       158 N    
ASPECT                   217 N    
ASSISTANCE               288 N    
ATTITUDE                 265 N    
BELIEF                   270 N    
BLAME                    293 N    
BLESSING                 277 N    
BOREDOM                  262 N    
BOTHER                   267 N    
CAPACITY                 293 N    
CAUSE                    287 N    
CHANCE                   254 N    
CHAOS                    299 N    
CIRCUMSTANCE             250 N    
COMPETENCE               256 N    
CONCEPT                  264 N    
CONCERT                  252 N    
CONCLUSION               278 N    
CONFIDENCE               270 N    
CONFUSION                282 N    
CONJUNCTION              288 N    
CONSCIENCE               255 N    
CONSEQUENCE              260 N    
CONSIDERATION            260 N    
CONTENT                  300 N    
CONTINUATION             288 N    
COURAGE                  277 N    
CRITERION                261 N    
DECISION                 297 N    
DEFINITION               262 N    
DELIGHT                  282 N    
DEMOCRACY                298 N    
DENIAL                   272 N    
DESPAIR                  279 N    
DETERMINATION            243 N    
DEVIL                    274 N    
DEVOTION                 231 N    
DIFFERENCE               270 N    
DIGNITY                  280 N    
DIMENSION                274 N    
DISCIPLINE               277 N    
DISCRETION               222 N    
DISPOSITION              251 N    
DISTINCTION              265 N    
DISTRESS                 282 N    
DIVERSITY                268 N    
DO                       276 N    
DOMINATION               275 N    
ECONOMY                  284 N    
EFFECT                   295 N    
EFFORT                   296 N    
EGO                      261 N    
EMOTION                  260 N    
ENTHUSIASM               266 N    
ESSENCE                  243 N    
ESTIMATE                 293 N    
EVEN                     283 N    
EXCEPTION                260 N    
EXCITEMENT               282 N    
EXPERIENCE               275 N    
EXPRESSION               297 N    
EXTENT                   267 N    
EXTRA                    262 N    
EXTREME                  265 N    
FACILITY                 279 N    
FAILURE                  282 N    
FANTASY                  295 N    
FATE                     255 N    
FEELING                  262 N    
FREEDOM                  277 N    
FUN                      295 N    
GOOD                     297 N    
GUESS                    247 N    
GUILT                    299 N    
HARM                     244 N    
HATRED                   239 N    
HAVE                     251 N    
HONESTY                  278 N    
HOPE                     261 N    
HYPOTHESIS               261 N    
IDEA                     259 N    
IDEAL                    253 N    
IDENTIFICATION           285 N    
IGNORANCE                249 N    
ILLUSION                 249 N    
IMAGINATION              274 N    
IMMORTALITY              209 N    
IMPATIENCE               257 N    
IMPORTANCE               244 N    
IMPRESSION               288 N    
IMPULSE                  271 N    
INDEPENDENCE             242 N    
INDICATION               282 N    
INFLUENCE                280 N    
INNOCENCE                247 N    
INSIGHT                  270 N    
INSISTENCE               262 N    
INSTANCE                 284 N    
INTEGRITY                247 N    
INTELLIGENCE             275 N    
INTENTION                285 N    
INTIMATE                 281 N    
IRONY                    243 N    
JOIN                     292 N    
JOY                      300 N    
JUSTIFICATION            219 N    
KNOW                     274 N    
KNOWLEDGE                278 N    
LAST                     299 N    
LEAST                    275 N    
LIKE                     286 N    
LOYALTY                  261 N    
LUCK                     275 N    
MAGIC                    257 N    
MAKE                     299 N    
MANNER                   297 N    
MANY                     276 N    
MASTERY                  279 N    
MEMORY                   284 N    
MERCY                    239 N    
MIGHT                    271 N    
MIRACLE                  282 N    
MISERY                   297 N    
MOOD                     234 N    
MORAL                    220 N    
MOTIVE                   255 N    
MUST                     297 N    
MYSTERY                  256 N    
NECESSITY                273 N    
NEGLECT                  282 N    
NONE                     288 N    
NONSENSE                 256 N    
OPINION                  285 N    
OPTIMISM                 240 N    
OR                       248 N    
OTHER                    275 N    
PASSION                  300 N    
PAST                     293 N    
PATIENCE                 266 N    
PERCEPTION               287 N    
PHILOSOPHY               257 N    
PRESTIGE                 248 N    
PRIDE                    270 N    
PRINCIPLE                245 N    
PURPOSE                  280 N    
PUT                      287 N    
QUALITY                  274 N    
REAL                     285 N    
REALITY                  296 N    
RECOGNITION              266 N    
REPUTATION               232 N    
REQUIREMENT              300 N    
RESENTMENT               252 N    
RESOLUTION               265 N    
RESPECT                  280 N    
RESPONSIBILITY           222 N    
RETENTION                280 N    
RISK                     290 N    
RULE                     286 N    
SALVATION                269 N    
SECURITY                 290 N    
SENSATION                265 N    
SENTIMENT                258 N    
SHAME                    287 N    
SIN                      273 N    
SOUL                     289 N    
SPIRIT                   296 N    
SPITE                    262 N    
SUCCESS                  295 N    
SUSPICION                265 N    
SYMPATHY                 278 N    
TALENT                   290 N    
TEMPTATION               265 N    
TENDENCY                 243 N    
THEORY                   287 N    
THOUGHT                  274 N    
TRADITION                291 N    
TRUST                    300 N    
TRUTH                    261 N    
TRY                      260 N    
UNCERTAINTY              237 N    
UPSET                    282 N    
VALUE                    260 N    
VARIETY                  297 N    
VIRTUE                   243 N    
WAY                      265 N    
WHILE                    204 N    
WILL                     275 N    
WISDOM                   275 N    
WISH                     270 N    
